version: "3.9"

services:
  securecheck:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securecheck_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app                # Mount local repo for live changes
      - ./reports:/app/reports  # Persist report outputs
    environment:
      - SPOTBUGS_HOME=/opt/spotbugs-4.8.2
      - PATH=/opt/spotbugs-4.8.2/bin:/app/venv/bin:$PATH
    command: >
      streamlit run ui.py 
      --server.port=8501 
      --server.address=0.0.0.0
    stdin_open: true
    tty: true
